#' @title Get General Linear Model Scores.
#'
#' @description Run a Mann-Whitney and general linear regression on a set of
#' prediction scores.
#'
#' @details This function takes a data frame with prediction data`these_predictions`
#' and executes statistical tests to find significant prediction scores based on
#' a categorical variable (i.e response, tumour grade, etc.). Currently, the
#' function expects the incoming data to be the score output from
#' [LundTax2023Classifier::predict_LundTax2023()], together with metadata
#' information of interest (e.g two level categorical) and subtype classification
#' information. In the future, this function will accept a seperate metadata
#' object and automagically extract all the other needed information form the
#' returned list from the previous mentioned function. The user have the option
#' to point the function to the categorical variable with `cat_variable`.
#' The return can be further subset by subtype by using the `this_subtype`
#' variable (one of Uro, BaSq, GU, Mes or ScNE).
#'
#' @param these_predictions Required parameter. A data frame with predictions
#' scores, subtype and metadata information.
#' @param these_samples_metadata Optional, a data frame with metadata of interest,
#' function will subset return to what samples are included in this object.
#' @param subtype_class Can be one of the following; 5class or 7class. Default is 5class.
#' @param this_subtype Optional parameter. Allows the user to subset the return 
#' to a specific subtype within the selected class. If not specified, the function 
#' will return a data frame not dependent on subtype.
#' @param cat_variable Required parameter. Specify the two level categorical variable you want to test for.
#' @param row_to_col Boolean parameter. Set to TRUE to transform row names of the 
#' metadata to a new column called sample_id. Default is FALSE.
#' @param sample_id_col Parameter dictating the column name with sample IDs, 
#' the function expects this column to be sample_id but the user can override 
#' this if they know the name for this column.
#' @param score_columns Optional parameter. Should be a list with column names 
#' with signatures of interest + the column sample_id. If not specified, 
#' the function assumes the signature nomenclature from the generated by 
#' [LundTax2023Classifier::predict_LundTax2023()] function.
#'
#' @return A data frame with statistical scores for the selected samples/subtypes.
#'
#' @import dplyr
#' @rawNamespace import(stats, except = c(filter, lag))
#'
#' @export
#'
#' @examples
#' #load packages
#' library(dplyr, stats)
#'
#' #run general linear models
#' my_glm = get_glmscores(these_predictions = swog_pred,
#'                        these_samples_metadata = swog_meta,
#'                        subtype_class = "5class",
#'                        this_subtype = "Uro",
#'                        cat_variable = "SEX",
#'                        sample_id_col = "ALTPATID")
#'
get_glmscores = function(these_predictions = NULL,
                         these_samples_metadata = NULL,
                         subtype_class = "5class",
                         this_subtype = NULL,
                         cat_variable = NULL,
                         row_to_col = FALSE,
                         sample_id_col = NULL,
                         score_columns = NULL){
  
  if(length(this_subtype) > 1){
    stop("Currently, only one subtype at the time is supported. For now, consider running this function multiple times for each subtype...")
  }

  #run helper
  this_object = int_predwrangler(these_predictions = these_predictions,
                                 these_samples_metadata = these_samples_metadata,
                                 subtype_class = subtype_class,
                                 this_subtype = this_subtype,
                                 cat_variable = cat_variable,
                                 row_to_col = row_to_col,
                                 sample_id_col = sample_id_col,
                                 score_columns = score_columns)

  #get the columns to test
  these_columns = c("proliferation_score", "immune141_up", "b_cells", "t_cells",
                    "t_cells_cd8", "nk_cells", "cytotoxicity_score",
                    "neutrophiles", "monocytic_lineage", "macrophages",
                    "m2_macrophages", "myeloid_dendritic_cells", "stromal141_up",
                    "endothelial_cells", "fibroblasts", "smooth_muscle")
  
  #check if data frame is empty and return it
  if(nrow(this_object) == 0){
    empty_df = data.frame(score = character(),
                          p_value = numeric(),
                          odds_ratio = numeric(),
                          conf_2.5 = numeric(),
                          conf_97.5 = numeric(),
                          subtype = factor())
    return(empty_df)
  }
  
  #mann whitney u-test
  message("Running Mann-Whitney U-test...")
  wilcox = lapply(this_object[,these_columns], function(x) wilcox.test(x ~ this_object[,cat_variable]))

  #generalized linear model
  message("Running Generalized Linear Model...")
  glm = lapply(this_object[,these_columns], function(x) glm(x ~ this_object[,cat_variable]))

  #helper function for running the stats on all scores
  extract_stats = function(wilcox,
                           glm){

    #initialize an empty data frame to store the results
    my_stats <- data.frame()

    #loop over each element in the wilcox object
    for (name in names(wilcox)){
      #create a new data frame for the current statistic
      stats <- data.frame(score = name)

      #extract p-value, odds ratio, and confidence intervals
      stats$p_value = wilcox[[name]]$p.value
      stats$odds_ratio = unname(unlist(exp(suppressMessages(glm[[name]]$coefficients))))[2]
      stats$conf_2.5 = unname(unlist(exp(suppressMessages(confint(glm[[name]])))))[2]
      stats$conf_97.5 = unname(unlist(exp(suppressMessages(confint(glm[[name]])))))[4]

      #bind the current results to the overall statistics data frame
      my_stats <- rbind(my_stats, stats)
    }
    return(my_stats)
  }

  #run helper
  stat_results = extract_stats(wilcox = wilcox,
                               glm = glm)

  if(!is.null(this_subtype)){
    stat_results$subtype = as.factor(this_subtype)
  }else{
    stat_results$subtype = as.factor("all")
  }

  #return results
  return(stat_results)
}
