#' @title Prediction Wrangler
#'
#' @description Internal function called by `get_glmscores`. 
#' Not meant for out-of-package usage.
#'
#' @details Takes an output from [LundTax2023Classifier::predict_LundTax2023()]
#' and pre-processing it so that statistical tests can be executed on this data.
#' For more info, see the documentation of `get_glmscores`.
#'
#' @param these_predictions Required. Output from [LundTax2023Classifier::predict_LundTax2023()].
#' @param these_samples_metadata Required. Metadata associated with he prediction output. 
#' Also possible for the user to provide a metadata subset with samples of interest, 
#' the return will be restricted to the samples within the specified group
#' @param score_columns Optional parameter. Should be a list with column names 
#' with signatures of interest + the column sample_id. If not specified, 
#' the function assumes the signature nomenclature from the generated by 
#' [LundTax2023Classifier::predict_LundTax2023()] function.
#' @param sample_id_col Parameter dictating the column name with sample IDs, 
#' the function expects this column to be sample_id but the user can override 
#' this if they know the name for this column.
#' @param row_to_col Boolean parameter. Set to TRUE to transform row names of the 
#' metadata to a new column called sample_id. Default is FALSE.
#' @param cat_variable Required parameter. This should be the categorical variable 
#' that is intended for testing. In addition, this should also be a variable of 
#' type factor, with exactly 2 levels.
#' @param subtype_class Can be one of the following; 5class or 7class. Default is 5class.
#' @param this_subtype Optional parameter. Allows the user to subset the return 
#' to a specific subtype within the selected class. If not specified, the function 
#' will return a data frame not dependent on subtype.
#'
#' @return A data frame ready for `get_glmscores`.
#'
#' @import dplyr
#'
#' @export
#'
#' @examples
#' #load packages
#' library(dplyr)
#'   
#' #run helper                                  
#' my_out = int_predwrangler(these_predictions = swog_pred, 
#'                           these_samples_metadata = swog_meta, 
#'                           subtype_class = "5class", 
#'                           this_subtype = "Uro", 
#'                           cat_variable = "SEX", 
#'                           sample_id_col = "ALTPATID")
#'                           
int_predwrangler = function(these_predictions = NULL,
                            these_samples_metadata = NULL,
                            score_columns = NULL,
                            sample_id_col = NULL,
                            row_to_col = FALSE,
                            cat_variable = NULL,
                            subtype_class = "5class",
                            this_subtype = NULL){
    
    #check predictions
    if(is.null(these_predictions)){
      stop("You must provide a valid dataset with predictions scores!")
    }
    
    #define correct column names
    new_names = c("sample_id", "proliferation_score", "immune141_up", "b_cells", "t_cells",
                  "t_cells_cd8", "nk_cells", "cytotoxicity_score", "neutrophiles", "monocytic_lineage",
                  "macrophages", "m2_macrophages", "myeloid_dendritic_cells", "stromal141_up", "endothelial_cells",
                  "fibroblasts", "smooth_muscle")
    
    #subset to columns of interest
    if(is.null(score_columns)){
      score_columns = c("sample_id", "ProliferationScore", "Immune141_UP", "B-cells", 
                        "T-cells", "T-cells CD8+", "NK-cells", "Cytotoxicity Score", 
                        "Neutrophils", "Monocytic lineage", "Macrophages", 
                        "M2 macrophage", "Myeloid Dendritic Cells", "Stromal141_UP",
                        "Endothelial cells", "Fibroblasts", "Smooth muscle")
    }
    
    #subset to the score columns of interest
    my_scores = these_predictions$scores %>% 
      tibble::rownames_to_column("sample_id") %>% 
      dplyr::select(all_of(score_columns)) %>%
      rename_at(vars(score_columns), ~ new_names)
    
    #get the subtype information
    if(subtype_class == "5class"){
      my_subtypes = as.data.frame(these_predictions$predictions_5classes) %>% 
        tibble::rownames_to_column("sample_id")
    }else if(subtype_class == "7class"){
      my_subtypes = as.data.frame(these_predictions$predictions_7classes) %>% 
        tibble::rownames_to_column("sample_id")
    }else{
      stop("only 5class and 7class subtypes are available...")
    }
    
    #rename subtype column
    colnames(my_subtypes)[2] = "subtype"
    
    #filter on subtypes
    if(!is.null(this_subtype)){
      message("Filtering prediction data on the selected subtype(s)...")
      my_subtypes = dplyr::filter(my_subtypes, subtype %in% this_subtype)
    }
    
    #subset to other relevant metadata columns
    if(is.null(these_samples_metadata)){
      stop("User must provide metadata with these_samples_metadata...")
    }else{
      if(row_to_col){
        my_metadata = these_samples_metadata %>% 
          tibble::rownames_to_column("sample_id")
      }
      
      #check the categorical variable
      if(!cat_variable %in% colnames(these_samples_metadata)){
        stop(paste0(cat_variable, " is not a valid column in the incoming metadata..."))
        if(!is.factor(these_samples_metadata[,cat_variable])){
          stop("cat_variable must be a factor...")
          if(length(levels(these_samples_metadata[,cat_variable])) != 2){
            stop("Levels of cat_variable must be exactly 2...")
          }
        }
      }
      
      #check smaple ID in metadata
      if(!"sample_id" %in% names(these_samples_metadata)){
        if(is.null(sample_id_col)){
          stop("Metadata has no column namned sample_id, consider running the function with sample_col, specifying the name of the column with sample IDs...")
        }else{
          colnames(these_samples_metadata)[colnames(these_samples_metadata) == sample_id_col] = "sample_id"
        }
      }
      
      my_metadata = these_samples_metadata %>%
        dplyr::select(all_of(c("sample_id", cat_variable)))
    }
    
    #combine data
    my_object = left_join(my_subtypes, my_scores, by = "sample_id")
    my_object = inner_join(my_metadata, my_object, by = "sample_id")
    message(paste0(nrow(my_object), " samples kept after filtering on subtype and metadata..."))
    
    #warn user how many samples are in the metadata and how many are kept after filtering
    no_scores = setdiff(my_metadata$sample_id, my_scores$sample_id)
    
    if(length(no_scores > 1)){
      message(paste0("Warning, ", length(no_scores), " samples are removed from the metadata, since they have no scores reported..."))
    }
    
    #reinstate factor type in categorical column
    my_object[,cat_variable] = as.factor(my_object[,cat_variable])
    
    #check that levels of subset data and remove subtypes that does not have two factors in the cat_variable
    if(length(levels(my_object[,cat_variable])) != 2){
      message("The resulting subset filter does not have 2 levels in the selected cat_variable...")
    }
    
    #check if there are actually two levels present of the selected variable
    if(length(unique(my_object[,cat_variable])) != 2){
      message("There are not two levels present in the selected column after filtering steps..")
      message("Returning empty data frame...")
      my_object[,] = matrix(ncol = ncol(my_object), rep(NA, prod(dim(my_object))))
      empty_object = my_object[complete.cases(my_object), ]
      return(empty_object)
    }
    
    return(my_object)
}
